#!/bin/bash
#set -x

CONTAINER_NAME=jlab
DOCKER_IMAGE=andrespp/jupyterlab

is_running(){
	#  Returns (echo) CONTAINER ID if container exists and is running, and
        # zero length string otherwise
	id=$(docker ps -q -f status=running -f name=$CONTAINER_NAME)
	echo $id
}

open_browser() {
	for i in `seq 10` ; do
		CONTAINER_ID=$(is_running)
		if [ ! -z $CONTAINER_ID ] ; then
			URL=$(docker exec $CONTAINER_NAME /entrypoint.sh geturl)
			if [ ! -z $URL ] ; then
				echo python -m webbrowser -t $URL
				python -m webbrowser -t $URL
				exit 0
			else
				continue
			fi
		else
			sleep 1
		fi
	done
}

## main()

# Check container status
CONTAINER_ID=$(is_running)

if [ -z $CONTAINER_ID ] ; then
	# Container not running, start it
	docker run --name jlab --rm -v "$PWD":/opt/app/data -p 8888:8888 \
		-p 8787:8787 -d -e KEYMAP=vim $DOCKER_IMAGE
	# Open JupyterLab
	open_browser
else
	echo JupyterLab already running \($CONTAINER_ID\). $URL
	URL=$(docker exec jlab /entrypoint.sh geturl)
	python -m webbrowser -t $URL
fi
